name: linkchat
description: Un chat para compartir tus links.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  shared_preferences: ^2.1.1
  lottie: ^2.3.2
  concentric_transition: ^1.0.3
  social_login_buttons: ^1.0.7
  image_picker: ^0.8.7
  path: ^1.8.3
  email_validator: ^2.1.17
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  firebase_messaging: ^14.6.1
  firebase_storage: ^11.2.1
  cloud_firestore: ^4.7.1
  custom_clippers: ^2.0.0
  simple_link_preview: ^1.0.2
  url_launcher: ^6.1.11
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: fonts/Manrope-Light.ttf
          weight: 300
        - asset: fonts/Manrope-Regular.ttf
          weight: 400
        - asset: fonts/Manrope-Medium.ttf
          weight: 500
        - asset: fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: fonts/Manrope-Bold.ttf
          weight: 700
        - asset: fonts/Manrope-ExtraBold.ttf
          weight: 800

